[project]
name = 'bitflow'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.sip-010-trait-ft-standard-v-1-1]
path = 'contracts/sip-010-trait-ft-standard-v-1-1.clar'
clarity_version = 3
epoch = 'latest'

[contracts.token-stx-v-1-2]
path = 'contracts/token-stx-v-1-2.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
